Fix gh-build failure bc. missing packageo
Error:
  npx --no-install antora --fetch antora-playbook.yml
  shell: /usr/bin/bash -e {0}
error: Generator not found or failed to load. Try installing the '@antora/site-generator-default' package.
Add the --stacktrace option to see the cause.